[package]
name = "CetusAggregator"
version = "0.1.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# published-at = "0x5fb33ae7b06dd05e4f70b9ff1ff0ae6e6198865bf85d97bfcfa81d242bcfd481"
published-at = "0xf9c6f78322ed667909e05f6b42b2f5a67af6297503c905335e02a15148e9440d"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.23.1", override = true }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", subdir = "sui", rev = "mainnet-v1.23.1" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "mainnet-v1.23.1" }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "mainnet-v1.23.1" }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "mainnet-v1.26.0", override = true }
KriyaAmm = { local = "../../externals/kriya-amm" }
KriyaClmm = { local = "../../externals/kriya-clmm" }
FlowxClmm = { local = "../../externals/flowx-clmm" }
FlowxAMM = { local = "../../externals/flowx-amm" }
TurbosDex = { local = "../../externals/turbos-dex" }
AftermathAMM = { local = "../../externals/aftermath/aftermath-amm" }
Afsui = { local = "../../externals/aftermath/staking" }
Hasui = { local = "../../externals/hasui" }
Vsui = { local = "../../externals/vsui" }
BlueMove = { local = "../../externals/bluemove" }
deepbookv3 = { local = "../../externals/deepbookv3/deepbook" }
token = { local = "../../externals/deepbookv3/token" }

[addresses]
cetus_aggregator = "0x0"
