[package]
name = "CetusAggregator"
version = "0.1.1"
published-at = "0x250aa7da667390273d5c10d46d601f55bdf9e9ab61848cc43cc70fdbf70e2ae6"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.23.1", override = true }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", subdir = "sui", rev = "mainnet-v1.23.1" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "mainnet-v1.23.1" }
DeepBook= { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "mainnet-v1.23.1" }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/clmmpool", rev = "mainnet-v1.23.1", override = true }
KriyaDex = { local = "../externals/kriya-dex" }
FlowxAMM = { local = "../externals/flowx-amm" }
TurbosDex = { local = "../externals/turbos-dex" } 
AftermathAMM = { local = "../externals/aftermath/aftermath-amm" }

[addresses]
cetus_aggregator = "0x0"
